/* USERS */
export const GET_COMPLAIN = "GET_COMPLAIN"
export const GET_COMPLAIN_SUCCESS = "GET_COMPLAIN_SUCCESS"
export const GET_COMPLAIN_FAIL = "GET_COMPLAIN_FAIL"


 /* add user
 */
export const ADD_NEW_COMPLAIN = "ADD_NEW_COMPLAIN"
export const ADD_COMPLAIN_SUCCESS = "ADD_COMPLAIN_SUCCESS"
export const ADD_COMPLAIN_FAIL = "ADD_COMPLAIN_FAIL"

/**
 * Edit user
 */
export const UPDATE_COMPLAIN = "UPDATE_COMPLAIN"
export const UPDATE_COMPLAIN_SUCCESS = "UPDATE_COMPLAIN_SUCCESS"
export const UPDATE_COMPLAIN_FAIL = "UPDATE_COMPLAIN_FAIL"

/**
 * Delete user
 */
export const DELETE_COMPLAIN = "DELETE_COMPLAIN"
export const DELETE_COMPLAIN_SUCCESS = "DELETE_COMPLAIN_SUCCESS"
export const DELETE_COMPLAIN_FAIL = "DELETE_COMPLAIN_FAIL"
